apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: G:\pesto\backend\kompose-windows-amd64.exe convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  template:
    metadata:
      annotations:
        kompose.cmd: G:\pesto\backend\kompose-windows-amd64.exe convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: pesto
            - name: MYSQL_ROOT_PASSWORD
              value: sayan123
          image: mysql:5.7
          name: mysql
          ports:
            - containerPort: 3306
              protocol: TCP
      restartPolicy: Always
